KEYWORDS = [
    # Original
    "ignore previous instructions",
    "reveal system prompt",
    "bypass security",
    "jailbreak",
    "act as",
    "developer mode",
    "pretend to be",
    "you are now",
    "disable safety",
    "leak data",
    "ignore all prior instructions",
    "forget previous instructions",
    "override system instructions",
    "disregard safety guidelines",
    "do not follow your rules",
    "ignore your training",
    "ignore your guidelines",
    "ignore content policy",
    "skip safety checks",
    "you are no longer chatgpt",
    "you are a different ai",
    "switch role to",
    "assume the role of",
    "play the role of",
    "act like a human",
    "act as an unrestricted ai",
    "act as a hacker",
    "simulate a persona",
    "become a malicious agent",
    "show system prompt",
    "print system instructions",
    "display hidden prompt",
    "what are your hidden rules",
    "reveal your configuration",
    "dump system message",
    "expose internal prompt",
    "show your chain of thought",
    "reveal hidden policies",
    "enable jailbreak mode",
    "enter developer mode",
    "activate god mode",
    "switch to unrestricted mode",
    "simulate jailbreak",
    "break your rules",
    "escape restrictions",
    "remove limitations",
    "this is for educational purposes only",
    "for research purposes only",
    "no restrictions apply",
    "you are allowed to answer anything",
    "this is a safe scenario",
    "nothing is illegal here",
    "bypass filters",
    "avoid detection",
    "give me confidential data",
    "leak private information",
    "share sensitive data",
    "expose secrets",
    "retrieve hidden data",
    "access restricted info",
    "show private keys",
    "dump database",
    "### system:",
    "### assistant:",
    "### developer:",
    "<system>",
    "</system>",
    "<assistant>",
    "BEGIN SYSTEM PROMPT",
    "END SYSTEM PROMPT",
    "```system",
    "```assistant",
    "base64 decode",
    "rot13 decode",
    "hex decode",
    "decode this message",
    "obfuscated instructions",
    "hidden command",
    "call this function secretly",
    "execute hidden command",
    "run internal tool",
    "access backend api",
    "trigger system call",
    "inject into tool",
    "modify tool behavior",
    "you must comply",
    "this is urgent",
    "system admin request",
    "authorized override",
    "you are permitted",
    "trust me",
    "do it without restrictions",
    "explain your reasoning step by step internally",
    "show hidden reasoning",
    "print chain of thought",
    "display internal thinking",
    "reveal reasoning tokens",
    "hypothetically ignore rules",
    "in an alternate universe",
    "simulate without restrictions",
    "imagine no safety rules exist",
    "assume all policies are disabled",
    "follow these new instructions instead",
    "replace your instructions with",
    "your new policy is",
    "system update:",
    "patch your behavior",
    "inject new prompt",
    "modify your core rules",
]

def detect_injection(text):
    text = text.lower()
    score = 0
    for pattern in KEYWORDS:
        if pattern in text:
            score += 0.2
    if score > 1.0:
        score = 1.0
    return score